export const getClientByPhoneNumberQuery = `SELECT
  A.ID_CLIENTE,
  B.ID_PRESTAMO,
  CONCAT_WS(' ', A.PRIMER_NOMBRE, A.SEGUNDO_NOMBRE, A.APELLIDO_PATERNO, A.APELLIDO_MATERNO) AS 'NOMBRE_COMPLETO',
  B.CUOTA
FROM T_CLIENTE A
LEFT JOIN T_PRESTAMO B ON (A.ID_CLIENTE = B.ID_CLIENTE)
WHERE A.CELULAR = ? AND B.ESTADO='VIGENTE';`

export const insertPaymentQuery = `INSERT INTO T_PAGO VALUES (?, ?, ?, ?)`

export const getClientReportQuery = `SELECT
  #A.ID_CLIENTE,
  CONCAT_WS(' ', A.PRIMER_NOMBRE, A.SEGUNDO_NOMBRE, A.APELLIDO_PATERNO, A.APELLIDO_MATERNO) AS 'NOMBRE_COMPLETO',
  #A.CELULAR,
  #B.ID_PRESTAMO,
  #B.FRECUENCIA,
  #B.FECHA_INICIO,
  #B.FECHA_FIN,
  #B.MONTO,
  #B.CUOTA,
  B.PLAZO,
  #LEAST(B.PLAZO, 1 + FN_DAYS_BETWEEN_TWO_DATES_WITHOUT_SUNDAYS(B.FECHA_INICIO, CURDATE(), B.FRECUENCIA)) AS 'CUOTA_ACTUAL',
  #LEAST(B.PLAZO, 1 + FN_DAYS_BETWEEN_TWO_DATES_WITHOUT_SUNDAYS(B.FECHA_INICIO, CURDATE(), B.FRECUENCIA)) * B.CUOTA AS 'MONTO_ESPERADO',
  FLOOR(IFNULL(C.TOTAL_PAGADO, 0) / B.CUOTA) AS 'CUOTAS_PAGADAS',
  #IFNULL(C.TOTAL_PAGADO, 0) AS 'MONTO_PAGADO',
  #LEAST(B.PLAZO, 1 + FN_DAYS_BETWEEN_TWO_DATES_WITHOUT_SUNDAYS(B.FECHA_INICIO, CURDATE(), B.FRECUENCIA)) - FLOOR(IFNULL(C.TOTAL_PAGADO, 0) / B.CUOTA) AS 'CUOTAS_ATRASADAS',
  LEAST(B.PLAZO, 1 + FN_DAYS_BETWEEN_TWO_DATES_WITHOUT_SUNDAYS(B.FECHA_INICIO, CURDATE(), B.FRECUENCIA)) * B.CUOTA - IFNULL(C.TOTAL_PAGADO, 0) AS 'MORA'
  #IFNULL(C.FECHA_ULTIMO_PAGO, '') AS 'FECHA_ULTIMO_PAGO',
  #IFNULL(FN_DAYS_BETWEEN_TWO_DATES_WITHOUT_SUNDAYS(DATE(C.FECHA_ULTIMO_PAGO), CURDATE(), 'DIARIO'), '') AS 'DIAS_ULTIMO_PAGO'
FROM T_CLIENTE A
LEFT JOIN T_PRESTAMO B ON (A.ID_CLIENTE = B.ID_CLIENTE)
LEFT JOIN (SELECT ID_PRESTAMO, SUM(MONTO) AS TOTAL_PAGADO, MAX(FECHA_HORA) AS FECHA_ULTIMO_PAGO FROM T_PAGO GROUP BY ID_PRESTAMO) C ON (B.ID_PRESTAMO = C.ID_PRESTAMO)
WHERE A.ID_CLIENTE=? AND B.ESTADO='VIGENTE'`

export const getClientInfoQuery = `SELECT
  TC.ID_CLIENTE,
  TC.DNI,
  CONCAT_WS(' ', TC.PRIMER_NOMBRE, TC.SEGUNDO_NOMBRE, TC.APELLIDO_PATERNO, TC.APELLIDO_MATERNO) AS 'NOMBRE_COMPLETO',
  TC.SEXO,
  TC.EDAD,
  TC.ESTADO_CIVIL,
  TC.DEPARTAMENTO,
  TC.CELULAR,
  TC.CORREO,
  TC.ESTADO
FROM T_CLIENTE TC
WHERE TC.DNI LIKE ?
ORDER BY TC.APELLIDO_PATERNO`
